#!/bin/env bash

export PATH="/opt/homebrew/bin:/opt/homebrew/opt/openjdk/bin:${PATH}"
export SHELL=/opt/homebrew/bin/bash

# https://www.addictivetips.com/mac-os/hide-default-interactive-shell-is-now-zsh-in-terminal-on-macos/
# Unfucking belivable
export BASH_SILENCE_DEPRECATION_WARNING=1
export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"

[[ -f /usr/local/etc/profile.d/bash_completion.sh ]] && source /usr/local/etc/profile.d/bash_completion.sh

if [[ -e $(brew --prefix asdf) ]]; then
  source "$(brew --prefix asdf)/libexec/asdf.sh"
  source "$(brew --prefix asdf)/etc/bash_completion.d/asdf.bash"
fi

alias gdu="${HOME}/go/bin/gdu"
alias unrar=7z
alias ls='ls -G'
alias ll='ls -l'
alias la='ls -la'

# x=shows/terraform/dev
# echo ${x}
# shows/terraform/dev
# echo ${x%%/*}
# shows
# echo ${x#*/}

if [[ -e /opt/homebrew/bin/ssh ]]; then
  alias ssh=/opt/homebrew/bin/ssh
  alias ssh-add=/opt/homebrew/bin/ssh-add
  alias ssh-agent=/opt/homebrew/bin/ssh-agent
  alias ssh-copy-id=/opt/homebrew/bin/ssh-copy-id
  alias ssh-keygen=/opt/homebrew/bin/ssh-keygen
  alias ssh-keyscan=/opt/homebrew/bin/ssh-keyscan
else
  # shellcheck disable=SC2263
  cat <<EoM
    Hey jtheo
    You're using default ssh that it's probably missing the Yubikey suport"
    To solve this problem, do:
      brew install openssh
    and then source again this file ${BASH_SOURCE[0]}
    Version available: $(ssh -V)
EoM
fi
# reset

echo
# shellcheck disable=SC2046
# cowsay $(fortune)
echo
