#!/bin/bash

alias pbcopy="xsel --clipboard"
alias open=xdg-open
alias kodimount='sshfs -o follow_symlinks  -o ro le:/storage/HD/ ${HOME}/Videos/kodi/ && open ${HOME}/Videos/kodi'
alias r4mount='sshfs -o follow_symlinks  -o ro r4:/media/bck ${HOME}/Videos/r4/ && open ${HOME}/Videos/r4'

export PATH=${PATH}:/usr/local/go/bin:${HOME}/bin
export TERM=screen-256color

alias ls='ls --color'
alias ll='ls -l'
