#!/bin/bash

function loadIfExists() {
  local include=${1}
  if [[ -f "${include}" ]]; then
    # shellcheck source=/dev/null
    source "${include}"
  fi
}

runningOS=$(uname -s)

includes=(
  variables
  functions
  git_functions
  git-completion.bash
  aliases
  aws_functions
  omega
  "${runningOS}"
)

BASE="${HOME}/.dotf"

if [[ $(uname -s) == "Darwin" ]]; then
  ulimit -n 25000
fi

for include in "${includes[@]}"; do
  # echo "Loading... ${include}"
  loadIfExists "${BASE}/${include}"
done

case ${SHELL##*/} in
  zsh) loadIfExists "${BASE}/zshrc" ;;
  bash) loadIfExists "${BASE}/prompt" ;;
  *) echo "What Shell is this one? <${SHELL}>" ;;
esac

if grep -q itv.com /etc/resolv.conf; then
  [[ -e ${BASE}/itv ]] && source "${BASE}/itv"
else
  [[ -e ${BASE}/personal ]] && source "${BASE}/personal"
fi

[[ -d ${HOME}/L ]] || mkdir -p "${HOME}/L"
