#!/usr/bin/env bash

# https://www.dwarmstrong.org/bashrc/
shopt -s histappend   # Require prompt write to history after every command and append to the history file, don’t overwrite it …
shopt -s checkwinsize # When resizing a terminal emulator, check the window size after each command and, if necessary, update the values of LINES and COLUMNS …
shopt -s cmdhist      # Save all lines of a multiple-line command in the same history entry …
shopt -s histreedit   # Re-edit a history substitution line if it failed ...
shopt -s histverify   # Edit a recalled history line before executing ...

# export PROMPT_COMMAND="history -a;history -c;history -r;${PROMPT_COMMAND}"

# shellcheck disable=SC2155
export HISTTIMEFORMAT="[$(tput setaf 6)%F %T$(tput sgr0)]: "
export HISTCONTROL=ignoreboth:ignoredups:erasedups:ignorespace
export HISTSIZE=20000
export HISTFILESIZE=500000

PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
# export PROMPT_COMMAND='printf "\033]0;%s at %s\007" "jtheo" "MAC"'

# Colour codes
# https://www.circuidipity.com/bashrc/
# https://www.dwarmstrong.org/bashrc/
GREEN="\\[\\e[1;32m\\]"
YELLOW="\\[\\e[1;33m\\]"
BLUE="\\[\\e[1;36m\\]"
WHITE="\\[\\e[1;37m\\]"
RED="\\[\\e[0;31m\\]"
# shellcheck disable=SC2034
MAGENTA="\\[\\e[1;35m\\]"
# shellcheck disable=SC2034
RESET="\\[\\e[0m\\]"

# shellcheck disable=2154
if grep -q itv.com /etc/resolv.conf; then
	HOST=itv
elif ${isMac}; then
	HOST=mac
else
	HOST=${HOSTNAME}
fi

# https://wiki.archlinux.org/title/Bash/Prompt_customization
# export PS1="${BLUE}\u${WHITE}@${GREEN}${HOST}${RESET} ${RED}\W${RESET}${YELLOW}$(parse_git_branch)${RESET}: "
# export PS1="\[\e[36;1m\]\u\[\e[0;32m\]@\[\e[32;1m\]${HOST}:\[\e[0;31m\] \W\[\e[0m\]\[\033[33m\]\$(parse_git_branch)\[\033[00m\]: "
export PS1="${BLUE}jtheo${WHITE}@${GREEN}${HOST} ${RED}\W${YELLOW}\$(parse_git_branch)${WHITE} $: "
