#!/bin/bash
autoload -Uz compinit && compinit

autoload -U select-word-style
select-word-style bash

autoload -Uz vcs_info
function precmd_vcs_info() { 
    vcs_info
}
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' formats " [%b]"

precmd_functions+=( precmd_vcs_info )
setopt prompt_subst


export PROMPT="%(?.√.!) %F{green}jt%F{white}@%F{blue}mac %F{red}%1~%F{yello}\$vcs_info_msg_0_%F{white} $: "


if command -v kubectl > /dev/null; then
    source <(kubectl completion zsh)
fi

# alias ls='ls --color'
# alias ll='ls -l'
alias gdu="${HOME}/go/bin/gdu"

if [[ ! -e ${SSH_AUTH_SOCH} ]] || [[ -z ${SSH_AGENT_PID} ]]; then
    eval "$(ssh-agent -s)"
fi

bindkey -e
