---
wtf:
  colors:
    border:
      focusable: "navy"
      focused: "green"
      normal: "gray"
    highlight:
      fore: "black"
      back: "gray"
    rows:
      even: yellow
      odd: white
    exitMessage:
      display: true
  term: "xterm-256color"
  grid:
    columns: [40, 70, 70, 70]
    rows: [5]
  refreshInterval: 5
  openUrlUtil:
    - /Applications/Firefox.app/Contents/MacOS/firefox
    - --new-tab

  mods:
    digitalclock:
      withDatePrefix: False
      dateFormat: "Monday 02 Jan 2006"
      color: green
      enabled: true
      # font: digitalfont
      font: bigfont
      hourFormat: 24
      position:
        top: 0
        left: 0
        height: 2
        width: 1
      refreshInterval: 1
      title: "clock"
      type: "digitalclock"

    clocks:
      colors:
        rows:
          even: "lightgreen"
          odd: "white"
      enabled: true
      title: World Clock
      locations:
        # From https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        Auckland: "Pacific/Auckland"
        Barcelona: "Europe/Madrid"
        Beijing: "Asia/Shanghai"
        Chicago: "America/Chicago"
        Denver: "America/Denver"
        Dubai: "Asia/Dubai"
        India: "Asia/Kolkata"
        London: "Europe/London"
        Los Angeles: "America/Los_Angeles"
        Melbourne: "Australia/Melbourne"
        Minsk: "Europe/Minsk"
        New York: "America/New York"
        Perth: "Australia/Perth"
        Rome: "Europe/Rome"
        Sidney: "Australia/Brisbane"
        Singapore: "Asia/Singapore"
        Tehran: "Asia/Tehran"
        Tokyo: "Asia/Tokyo"
        Vancouver: "America/Vancouver"
      position:
        top: 2
        left: 0
        height: 4
        width: 1
      refreshInterval: 15
      # sort: "alphabetical"
      sort: "chronological"

    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 6
        left: 0
        height: 3
        width: 1
      refreshInterval: 10
      showCPU: true
      showMem: true
      showSwp: true

    # textfile:
    #   enabled: true
    #   focusChar: 0
    #   filePath: "~/.config/wtf/fortune.txt"
    #   focusable: false
    #   format: false
    #   position:
    #     top: 8
    #     left: 2
    #     height: 2
    #     width: 1
    #   refreshInterval: 1800
    #   title: "Fortune"
    #   formatStyle: "dracula"

    lobste:
      title: lobste.rs
      enabled: true
      focusChar: 1
      showSource: false
      feeds:
        - https://lobste.rs/newest.rss
      feedLimit: 25
      position:
        top: 0
        left: 1
        height: 5
        width: 1
      refreshInterval: 2h
      type: feedreader

    hackernews:
      enabled: true
      focusChar: 2
      numberOfStories: 15
      position:
        top: 5
        left: 1
        height: 3
        width: 1
      storyType: top
      refreshInterval: 2h

    r-pe:
      enabled: true
      focusChar: 3
      numberOfPosts: 10
      position:
        top: 8
        left: 1
        height: 2
        width: 1
      refreshInterval: 6h
      sortOrder: new
      subreddit: "platform_engineering"
      topTimePeriod: day
      type: subreddit

    r-go:
      enabled: true
      focusChar: 4
      numberOfPosts: 20
      position:
        top: 0
        left: 2
        height: 4
        width: 1
      refreshInterval: 6h
      sortOrder: new
      subreddit: "golang"
      topTimePeriod: day
      type: subreddit

    r-k8s:
      enabled: true
      focusChar: 6
      numberOfPosts: 10
      position:
        top: 4
        left: 2
        height: 2
        width: 1
      refreshInterval: 15m
      sortOrder: new
      subreddit: "kubernetes"
      topTimePeriod: week
      type: subreddit

    r-sre:
      enabled: true
      focusChar: 8
      numberOfPosts: 10
      position:
        top: 6
        left: 2
        height: 2
        width: 1
      refreshInterval: 6h
      sortOrder: new
      subreddit: "sre"
      topTimePeriod: week
      type: subreddit

    r-terraform:
      enabled: true
      focusChar: "b"
      numberOfPosts: 10
      position:
        top: 8
        left: 2
        height: 2
        width: 1
      refreshInterval: 6h
      sortOrder: new
      subreddit: "terraform"
      topTimePeriod: week
      type: subreddit

    r-neovim:
      enabled: true
      focusChar: 5
      numberOfPosts: 20
      position:
        top: 0
        left: 3
        height: 4
        width: 2
      refreshInterval: 6h
      sortOrder: new
      subreddit: "neovim"
      topTimePeriod: week
      type: subreddit

    r-linux:
      enabled: true
      focusChar: 7
      numberOfPosts: 10
      position:
        top: 4
        left: 3
        height: 2
        width: 2
      refreshInterval: 6h
      sortOrder: new
      subreddit: "linux"
      topTimePeriod: week
      type: subreddit

    # r-tmux:
    #   enabled: true
    #   focusChar: 9
    #   numberOfPosts: 10
    #   position:
    #     top: 4
    #     left: 3
    #     height: 2
    #     width: 2
    #   refreshInterval: 6h
    #   sortOrder: new
    #   subreddit: "tmux"
    #   topTimePeriod: week
    #   type: subreddit

    r-aws:
      enabled: true
      focusChar: 9
      numberOfPosts: 10
      position:
        top: 6
        left: 3
        height: 2
        width: 2
      refreshInterval: 6h
      sortOrder: new
      subreddit: "aws"
      topTimePeriod: week
      type: subreddit

    r-wezterm:
      enabled: true
      focusChar: a
      numberOfPosts: 10
      position:
        top: 8
        left: 3
        height: 2
        width: 2
      refreshInterval: 6h
      sortOrder: new
      subreddit: "wezterm"
      topTimePeriod: week
      type: subreddit

    # r-rust:
    #   enabled: true
    #   focusChar: a
    #   numberOfPosts: 10
    #   position:
    #     top: 8
    #     left: 2
    #     height: 2
    #     width: 1
    #   refreshInterval: 6h
    #   sortOrder: new
    #   subreddit: "rust"
    #   topTimePeriod: week
    #   type: subreddit
