---
wtf:
  colors:
    border:
      focusable: "navy"
      focused: "green"
      normal: "gray"
    highlight:
      fore: "black"
      back: "gray"
    rows:
      even: yellow
      odd: white
    exitMessage:
      display: true
  term: "xterm-256color"
  grid:
    # columns: [40, 70, 70, 70]
    columns: [35, 35, 80]
    rows: [5]
  refreshInterval: 5
  openUrlUtil:
    - /Applications/Firefox.app/Contents/MacOS/firefox
    - --new-tab

  mods:
    digitalclock:
      withDatePrefix: False
      dateFormat: "Monday 02 Jan 2006"
      color: green
      enabled: true
      # font: digitalfont
      font: bigfont
      hourFormat: 24
      position:
        top: 5
        left: 0
        height: 2
        width: 1
      refreshInterval: 1
      title: "clock"
      type: "digitalclock"

    clocks:
      colors:
        rows:
          even: "lightgreen"
          odd: "white"
      enabled: true
      title: World Clock
      locations:
        # From https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        Auckland: "Pacific/Auckland"
        Barcelona: "Europe/Madrid"
        Beijing: "Asia/Shanghai"
        Chicago: "America/Chicago"
        Denver: "America/Denver"
        Dubai: "Asia/Dubai"
        India: "Asia/Kolkata"
        London: "Europe/London"
        Los Angeles: "America/Los_Angeles"
        Melbourne: "Australia/Melbourne"
        Minsk: "Europe/Minsk"
        New York: "America/New York"
        Perth: "Australia/Perth"
        Rome: "Europe/Rome"
        Sidney: "Australia/Brisbane"
        Singapore: "Asia/Singapore"
        Tehran: "Asia/Tehran"
        Tokyo: "Asia/Tokyo"
        Vancouver: "America/Vancouver"
      position:
        top: 7
        left: 0
        height: 3
        width: 1
      refreshInterval: 15
      # sort: "alphabetical"
      sort: "chronological"

    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 5
        left: 1
        height: 3
        width: 1
      refreshInterval: 10
      showCPU: true
      showMem: true
      showSwp: true

    lobste:
      title: lobste.rs
      enabled: true
      focusChar: 1
      showSource: false
      feeds:
        - https://lobste.rs/newest.rss
      feedLimit: 20
      position:
        top: 0
        left: 0
        height: 5
        width: 2
      refreshInterval: 2h
      type: feedreader

    hackernews:
      enabled: true
      focusChar: 2
      numberOfStories: 20
      position:
        top: 0
        left: 2
        height: 5
        width: 1
      storyType: top
      refreshInterval: 2h

    r-go:
      enabled: true
      focusChar: 3
      numberOfPosts: 20
      position:
        top: 0
        left: 3
        height: 5
        width: 1
      refreshInterval: 6h
      sortOrder: new
      subreddit: "golang"
      topTimePeriod: day
      type: subreddit

    r-pe:
      enabled: true
      # focusChar: 4
      numberOfPosts: 10
      position:
        top: 5
        left: 2
        height: 3
        width: 1
      refreshInterval: 6h
      sortOrder: new
      subreddit: "platform_engineering"
      topTimePeriod: day
      type: subreddit

    r-sre:
      enabled: true
      # focusChar: 8
      numberOfPosts: 10
      position:
        top: 5
        left: 3
        height: 3
        width: 1
      refreshInterval: 6h
      sortOrder: new
      subreddit: "sre"
      topTimePeriod: week
      type: subreddit

    # r-devops:
    #   enabled: true
    #   # focusChar: "b"
    #   numberOfPosts: 10
    #   position:
    #     top: 5
    #     left: 2
    #     height: 3
    #     width: 1
    #   refreshInterval: 6h
    #   sortOrder: new
    #   subreddit: "devops"
    #   topTimePeriod: week
    #   type: subreddit

    r-neovim:
      enabled: true
      # focusChar: 5
      numberOfPosts: 10
      position:
        top: 8
        left: 3
        height: 3
        width: 1
      refreshInterval: 6h
      sortOrder: new
      subreddit: "neovim"
      topTimePeriod: week
      type: subreddit

    r-k8s:
      enabled: true
      # focusChar: 6
      numberOfPosts: 10
      position:
        top: 8
        left: 2
        height: 3
        width: 1
      refreshInterval: 15m
      sortOrder: new
      subreddit: "kubernetes"
      topTimePeriod: week
      type: subreddit

    # r-linux:
    #   enabled: true
    #   # focusChar: 7
    #   numberOfPosts: 10
    #   position:
    #     top: 8
    #     left: 1
    #     height: 3
    #     width: 1
    #   refreshInterval: 6h
    #   sortOrder: new
    #   subreddit: "linux"
    #   topTimePeriod: week
    #   type: subreddit

    cryptolive:
      enabled: true
      focusChar: 0
      position:
        top: 8
        left: 1
        height: 2
        width: 1
      updateInterval: 15
      currencies:
        BTC:
          displayName: Bitcoin
          to:
            - GBP
        ETH:
          displayName: Ethereum
          to:
            - GBP
        XRP:
          displayName: XRP
          to:
            - GBP
        # LTC:
        #   displayName: Litecoin
        #   to:
        #     - GBP
      colors:
        from:
          name: coral
          displayName: grey
        to:
          name: white
          price: green
        top:
          from:
            name: grey
            displayName: coral
          to:
            name: red
            field: white
            value: green

